site_name: "Introduction to Computing"
site_author: "John Foley <johnf@middlebury.edu>"
site_description: "Public Course Website for CS145 F2021 at Middlebury College."
docs_dir: "src"
use_directory_urls: false
repo_url: "https://github.com/jjfiv/cs145-f2021"
repo_name: "Github"
edit_uri: "tree/master/src/"
theme: 
    name: "readthedocs"
    custom_dir: "customize"
markdown_extensions:
    - extra
    - md_in_html
    - sane_lists
    - tables
    - nl2br
    - mdx_math
    - attr_list
nav:
    - index.md
    - syllabus.md
    - "Canvas": 'https://middlebury.instructure.com/courses/9217'
